package com.fbint.collector.ui.setup

import android.Manifest
import android.content.pm.PackageManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.Preview
import androidx.camera.core.resolutionselector.AspectRatioStrategy
import androidx.camera.core.resolutionselector.ResolutionSelector
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.LocalLifecycleOwner
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.navigation.NavHostController
import com.fbint.collector.data.repository.ConfigRepository
import com.fbint.collector.ui.nav.Routes
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.barcode.common.Barcode
import com.google.mlkit.vision.common.InputImage
import dagger.hilt.android.lifecycle.HiltViewModel
import java.util.concurrent.Executors
import javax.inject.Inject

@HiltViewModel
class QrScanViewModel @Inject constructor(
    private val config: ConfigRepository,
) : ViewModel() {
    fun consume(payload: String): Boolean {
        val parsed = SetupConfigCodec.decode(payload) ?: return false
        if (parsed.baseUrl.isBlank() || parsed.apiKey.isBlank() || parsed.connectionId().isBlank()) return false
        config.saveServerConfig(parsed.baseUrl, parsed.apiKey, parsed.connectionId(), parsed.projectName, parsed.workspaceId)
        return true
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QrScanScreen(
    nav: NavHostController,
    vm: QrScanViewModel = hiltViewModel(),
) {
    var scanError by remember { mutableStateOf<String?>(null) }
    val ctx = LocalContext.current
    var hasPermission by remember {
        mutableStateOf(
            ContextCompat.checkSelfPermission(ctx, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED
        )
    }
    val permissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) {
        hasPermission = it
    }

    LaunchedEffect(Unit) {
        if (!hasPermission) permissionLauncher.launch(Manifest.permission.CAMERA)
    }

    var completed by remember { mutableStateOf(false) }
    val acceptPayload: (String) -> Boolean = { payload ->
        if (completed) true else {
            val accepted = vm.consume(payload)
            if (accepted) {
                completed = true
                nav.navigate(Routes.SPLASH) { popUpTo(0) { inclusive = true } }
            } else scanError = "This is not a valid Ahlan setup QR. Use the code generated by the admin app."
            accepted
        }
    }
    val imagePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        if (uri != null) {
            val reader = BarcodeScanning.getClient()
            try {
                reader.process(InputImage.fromFilePath(ctx, uri))
                    .addOnSuccessListener { codes ->
                        val value = codes.firstOrNull { it.format == Barcode.FORMAT_QR_CODE }?.rawValue
                        if (value == null) scanError = "No QR code found. Choose a clear image of the complete code."
                        else acceptPayload(value)
                    }
                    .addOnFailureListener { scanError = "Could not read that QR image. Try another image." }
                    .addOnCompleteListener { reader.close() }
            } catch (_: Exception) { reader.close(); scanError = "Could not open that image." }
        }
    }

    Scaffold(topBar = { TopAppBar(title = { Text("Scan setup QR") }) }) { padding ->
        Column(
            modifier = Modifier.fillMaxSize().padding(padding),
            verticalArrangement = Arrangement.Top,
        ) {
            Button(onClick = { imagePicker.launch("image/*") }, modifier = Modifier.padding(12.dp)) {
                Text("Import setup QR image")
            }
            if (!hasPermission) scanError?.let { Text(it, modifier = Modifier.padding(12.dp)) }
            if (hasPermission) {
                Box(modifier = Modifier.weight(1f).fillMaxWidth()) {
                    QrCameraPreview(onPayload = acceptPayload, onError = { scanError = it })
                }
                scanError?.let { Text(it, modifier = Modifier.padding(16.dp)) }
                Text(
                    "Hold the phone over the admin device's setup QR. Make sure you trust the source — the QR contains an API key.",
                    modifier = Modifier.padding(16.dp),
                )
            } else {
                Column(
                    modifier = Modifier.fillMaxSize().padding(24.dp),
                    verticalArrangement = Arrangement.Center,
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Text("Camera permission is required to scan the setup QR.")
                    Spacer(Modifier.height(16.dp))
                    Button(onClick = { permissionLauncher.launch(Manifest.permission.CAMERA) }) {
                        Text("Grant camera permission")
                    }
                }
            }
        }
    }
}

@Composable
@androidx.annotation.OptIn(androidx.camera.core.ExperimentalGetImage::class)
private fun QrCameraPreview(onPayload: (String) -> Boolean, onError: (String) -> Unit) {
    val ctx = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val scanGate = remember { QrScanGate() }
    val scanner = remember { BarcodeScanning.getClient() }
    val analysisExecutor = remember { Executors.newSingleThreadExecutor() }
    val disposed = remember { java.util.concurrent.atomic.AtomicBoolean(false) }
    var cameraProvider by remember { mutableStateOf<ProcessCameraProvider?>(null) }
    DisposableEffect(Unit) {
        onDispose {
            disposed.set(true)
            cameraProvider?.unbindAll()
            scanner.close()
            analysisExecutor.shutdown()
        }
    }

    AndroidView(
        modifier = Modifier.fillMaxSize(),
        factory = { context ->
            val previewView = PreviewView(context)
            previewView.scaleType = PreviewView.ScaleType.FIT_CENTER

            val providerFuture = ProcessCameraProvider.getInstance(context)
            providerFuture.addListener({
                if (disposed.get()) return@addListener
                try {
                val provider = providerFuture.get()
                cameraProvider = provider
                val preview = Preview.Builder().build().also { it.setSurfaceProvider(previewView.surfaceProvider) }
                val resolution = ResolutionSelector.Builder()
                    .setAspectRatioStrategy(AspectRatioStrategy.RATIO_16_9_FALLBACK_AUTO_STRATEGY)
                    .build()
                val analysis = ImageAnalysis.Builder()
                    .setResolutionSelector(resolution)
                    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                    .build()
                analysis.setAnalyzer(analysisExecutor) { proxy ->
                    val media = proxy.image
                    if (media == null || scanGate.consumed) { proxy.close(); return@setAnalyzer }
                    val image = InputImage.fromMediaImage(media, proxy.imageInfo.rotationDegrees)
                    scanner.process(image)
                        .addOnSuccessListener { barcodes ->
                            val payload = barcodes.firstOrNull { it.format == Barcode.FORMAT_QR_CODE }?.rawValue
                            if (!payload.isNullOrBlank()) {
                                scanGate.offer(payload, onPayload)
                            }
                        }
                        .addOnFailureListener { onError("Camera detection failed. Reopen the scanner or import a QR image.") }
                        .addOnCompleteListener { proxy.close() }
                }
                provider.unbindAll()
                provider.bindToLifecycle(lifecycleOwner, CameraSelector.DEFAULT_BACK_CAMERA, preview, analysis)
                } catch (_: Exception) { onError("Could not open the camera. Import a QR image instead.") }
            }, ContextCompat.getMainExecutor(context))

            previewView
        },
    )
}
